server:
  port: 8082     # 服务端口号
spring:
  application:
    name: file-upload       # 服务名
  servlet:
    multipart:
      max-file-size: 10MB   # 限制文件上传的大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka       # 注册中心路径
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1                  #   防止别人拿到主机名
